### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by amanmdesai**
a few more fixes

### CODE REVIEW

**Comment by amanmdesai** [comment]
Not sure why the tests are failing.

**Comment by amanmdesai** [comment]
@vvolkl shall I update actions/checkout@v2 to actions/checkout@v3 in the test.yml

**Comment by vvolkl** [comment]
Hi Aman, no,  once in a while there is an EOS failure when trying to fetch the CVMFS packages, when github-action-cvmfs fails it just needs to be restarted.

**Comment by vvolkl** [comment]
Thanks for the fixes!

**Comment by amanmdesai** [comment]
> Hi Aman, no, once in a while there is an EOS failure when trying to fetch the CVMFS packages, when github-action-cvmfs fails it just needs to be restarted.

Oh I see. Thanks.

**Pull request merged**
